version: "3"

services:
  # mysql:
  #   image: mysql:8.0.30
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: account
  #   ports:
  #     - "33061:3306"
  #   volumes:
  #     - mysql_volume:/var/lib/mysql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: example
    ports:
      - 27017:27017
    volumes:
      - ./mock/mongo/initdb.d:/docker-entrypoint-initdb.d
      # - ./mongo:/data/db
      # - ./mongo:/data/configdb

  redis:
    container_name: redis
    image: redis:alpine3.17
    ports:
      - 6379:6379