version: "3"

services:
  mysql:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: account
    ports:
      - "33061:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
    driver: local
